Add more padding on POD processing time
pulibrary/lib_jobs pull request #312
Opened 2022-05-09 21:21 UTC by kevinreiss

Per @mzelesky. When large groups of records  in this set are touched the previous window will come up before Alma has completed the process.

2022-05-09 21:31 UTC, sandbergja requested changes
Thanks, @kevinreiss.  I think one comment needs to be updated, and then we are good.

2022-05-09 21:31 UTC, sandbergja commented on config/schedule.rb
> +every 1.day, at: '11:30 am', roles: [:prod] do # The server is in UTC, so this is 6:30 UTC
```suggestion
every 1.day, at: '11:30 am', roles: [:prod] do # The server is in UTC, so this refers to 11:30 UTC
```

2022-05-12 21:29 UTC, kevinreiss commented
@sandbergja I think this one is okay now. Thanks for the feedback.

2022-05-12 21:29 UTC, sandbergja approved these changes

2022-05-12 21:32 UTC, merged