Update readme.md
pulibrary/lib_jobs pull request #641
Opened 2023-09-18 15:20 UTC by regineheberlein

Do not merge until the workflow has been implemented

2023-10-06 15:53 UTC, sandbergja requested changes
Thanks, @regineheberlein !  It appears that mermaid doesn't like semicolons in the steps, so doesn't generate the chart.  Okay to change them to commas?

2023-10-06 15:53 UTC, sandbergja commented on docs/aspace2alma/readme.md
> +Lib Jobs->>lib-sftp: sends MARC-XML file to lib-sftp; renames old file
```suggestion
Lib Jobs->>lib-sftp: sends MARC-XML file to lib-sftp, renames old file
```

2023-10-06 15:53 UTC, sandbergja commented on docs/aspace2alma/readme.md
> +Lib Jobs->>lib-sftp: aspace2alma requests barcode report at 3:30am daily; deletes report once downloaded
```suggestion
Lib Jobs->>lib-sftp: aspace2alma requests barcode report at 3:30am daily, deletes report once downloaded
```

2023-10-06 16:01 UTC, regineheberlein commented
Thanks @sandbergja

2023-10-17 15:07 UTC, sandbergja approved these changes
Thanks, @regineheberlein !

2023-10-17 15:07 UTC, merged