Implements separate ApplicationJobs for generating different AbIDs for those linked to ArchivesSpace records and those linked to MARC records
pulibrary/lib_jobs pull request #98
Opened 2021-03-18 05:28 UTC by jrgriffiniii

Advances #96 with the following:
- Implementing ApplicationJob Classes for separately generating AbsoluteIds for ArchivesSpace and MARC source records
- Restructuring the AbsoluteId Model in order to ensure that MARC-only AbsoluteIds can be generated

2021-03-18 06:13 UTC, jrgriffiniii commented
d537410, 918d4c8, and 325ca8b were necessary to restore the tests to passing on CircleCI. I can rebase this, or consider this blocked until #92 is merged (my preference is for the latter).

2021-04-01 17:43 UTC, jrgriffiniii commented
Blocked by https://github.com/pulibrary/lib_jobs/pull/92

2021-04-01 18:10 UTC, jrgriffiniii commented
Many of the bugs which were fixed within https://github.com/pulibrary/lib_jobs/tree/absolute-ids-top-containers-refactor seem to have been introduced in this PR. I am fixing these now.

2021-04-01 19:41 UTC, tpendragon requested changes

2021-04-01 19:41 UTC, tpendragon commented on app/jobs/absolute_id_create_record_job.rb
> +class AbsoluteIdCreateRecordJob < ApplicationJob
This class is untested: https://1347-165745983-gh.circle-artifacts.com/0/coverage/index.html#d46fab0128696ee76db1970302d5be0a0905ae06

2021-04-01 19:41 UTC, tpendragon commented on app/jobs/absolute_id_create_marc_source_record_job.rb
> +  def current_user
current_user/current_client are uncovered:

https://1347-165745983-gh.circle-artifacts.com/0/coverage/index.html#063449fe3044a43f7ce1474652937a6bd6110d32

2021-04-21 17:42 UTC, tpendragon approved these changes

2021-04-21 17:48 UTC, merged